<?xml version="1.0" standalone='yes'?>
<!DOCTYPE biosis SYSTEM "biosis.dtd" [
<!ENTITY amp "&#38;#38;">
<!ENTITY apos "&#39;">
<!ELEMENT biosis (DOC)+>
<!ELEMENT DOC ((DOCNO|ArticleTitle|AbstractText|Affiliation|AU|CASRegistryNumber|Coden|EntryMonth|Keyword|Language|MeshHeading|SecondarySourceID|Source|Year)*)>
<!ELEMENT DOCNO (#PCDATA)>
<!ELEMENT ArticleTitle (#PCDATA)>
<!ELEMENT AbstractText (#PCDATA)>
<!ELEMENT Affiliation (#PCDATA)>
<!ELEMENT AU (#PCDATA)>
<!ELEMENT CASRegistryNumber (#PCDATA)>
<!ELEMENT Coden (#PCDATA)>
<!ELEMENT EntryMonth (#PCDATA)>
<!ELEMENT Keyword (#PCDATA)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT MeshHeading (#PCDATA)>
<!ELEMENT SecondarySourceID (#PCDATA)>
<!ELEMENT Source (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
]>

<biosis>
<DOC>
<EntryMonth>200005</EntryMonth>
<CASRegistryNumber>10102-43-9</CASRegistryNumber>
<CASRegistryNumber> 10102-43-9</CASRegistryNumber>
<CASRegistryNumber> 10024-97-2</CASRegistryNumber>
<CASRegistryNumber> 7664-41-7</CASRegistryNumber>
<CASRegistryNumber> 630-08-0</CASRegistryNumber>
<CASRegistryNumber> 124-38-9</CASRegistryNumber>
<CASRegistryNumber> 74-90-8</CASRegistryNumber>
<CASRegistryNumber> 74-82-8</CASRegistryNumber>
<Language>eng</Language>
<Coden>BIRTE</Coden>
<MeshHeading>CONSERVATION OF NATURAL RESOURCES</MeshHeading>
<MeshHeading>BIOCHEMISTRY/METHODS</MeshHeading>
<MeshHeading>BIOCHEMISTRY</MeshHeading>
<MeshHeading>POISONING</MeshHeading>
<MeshHeading>ANIMALS, LABORATORY</MeshHeading>
<MeshHeading>AIR POLLUTION</MeshHeading>
<MeshHeading>SOIL POLLUTANTS</MeshHeading>
<MeshHeading>WATER POLLUTION</MeshHeading>
<MeshHeading>TREES</MeshHeading>
<MeshHeading>PLANTS</MeshHeading>
<MeshHeading>PLANTS</MeshHeading>
<MeshHeading>PLANTS</MeshHeading>
<ArticleTitle>NO and N2O formation during the combustion of wood, straw, malt waste and peat.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  The NO and N2O formation behavior of six biofuels (spruce wood, beech wood, alder wood, straw, malt waste, peat) was studied in a formation-rate unit under conditions relevant to a fluidized-bed combustor and a grate-furnace. The concentrations of CO2, CO, CH4, other hydrocarbons, NO, N2O, HCN, and NH3 were measured in the flue gas, shortly after the burning fuel particles. Most of the fuel nitrogen was released during devolatilization (66-75%). Relatively high conversions to NO were found. N2O was formed but also rapidly destroyed by the reaction: N2O + H - N2 + OH. HCN was also formed in quantities similar to NH3 even during wood combustion. The HCN3 ratios seemed to depend on the fuel H/N ratios. The experimental results supported the hypothesis that the nitrogen of wood and other biofuels also exists in heterocyclic structures. With the proposed NO and N2O formation mechanism the  effects of fuel nitrogen content, temperature and oxygen partial pressure can be explained./METHODS</AbstractText>
<AU>WINTER F</AU>
<AU>WARTHA C</AU>
<AU>HOFBAUER H</AU>
<Affiliation>Institute of Chemical Engineering, Fuel Technology and Environmental Technology, Getreidemarkt 9, A-1060, Vienna, Austria.</Affiliation>
<Year>1999</Year>
<Source>BIORESOURCE TECHNOLOGY; 70 (1). 1999. 39-49.</Source>
<Keyword>General Biology-Conservation</Keyword>
<Keyword>Biochemical Methods-General</Keyword>
<Keyword>Biochemical Studies-General</Keyword>
<Keyword>Toxicology-General</Keyword>
<Keyword>Public Health: Environmental Health-Air</Keyword>
<Keyword>Forestry and Forest Products</Keyword>
<Keyword>Coniferopsida</Keyword>
<Keyword>Betulaceae</Keyword>
<Keyword>Fagaceae</Keyword>
<SecondarySourceID>BIOSIS/00/03740</SecondarySourceID>
<DOCNO>BIOSIS/00/03740</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<CASRegistryNumber>7440-66-6</CASRegistryNumber>
<CASRegistryNumber> 7440-66-6</CASRegistryNumber>
<CASRegistryNumber> 7440-50-8</CASRegistryNumber>
<CASRegistryNumber> 7440-47-3</CASRegistryNumber>
<CASRegistryNumber> 7440-43-9</CASRegistryNumber>
<CASRegistryNumber> 7440-02-0</CASRegistryNumber>
<CASRegistryNumber> 7439-96-5</CASRegistryNumber>
<CASRegistryNumber> 7439-92-1</CASRegistryNumber>
<Language>rus</Language>
<Coden>AGKYA</Coden>
<MeshHeading>AIR POLLUTION</MeshHeading>
<MeshHeading>SOIL POLLUTANTS</MeshHeading>
<MeshHeading>WATER POLLUTION</MeshHeading>
<MeshHeading>FERTILIZERS</MeshHeading>
<MeshHeading>SOIL</MeshHeading>
<ArticleTitle>Effect of urban sewage sediments on the behavior of heavy metals in the soil-plant system.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  The features of the migration of heavy metals from the sediments of urban sewage were studied in the sediment-soil-plant system. Experiments were carried out with soddy-podzolic soil and leached chernozem.</AbstractText>
<AU>KASATIKOV VA</AU>
<AU>KASATIKOVA SM</AU>
<AU>SULTANOV MM</AU>
<AU>USENKO VI</AU>
<AU>SHABARDINA NN</AU>
<Year>1999</Year>
<Source>AGROKHIMIYA; 0 (3). 1999. 56-60.</Source>
<Keyword>Public Health: Environmental Health-Air</Keyword>
<Keyword>Soil Science-Fertility and Applied Studies (1970- )</Keyword>
<SecondarySourceID>BIOSIS/00/03741</SecondarySourceID>
<DOCNO>BIOSIS/00/03741</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>ECOTE</Coden>
<MeshHeading>ANIMALS/GENETICS</MeshHeading>
<MeshHeading>ECOLOGY</MeshHeading>
<MeshHeading>POISONING</MeshHeading>
<MeshHeading>ANIMALS, LABORATORY</MeshHeading>
<MeshHeading>FISHES</MeshHeading>
<MeshHeading>FISHES</MeshHeading>
<ArticleTitle>A population genetic analysis of the potential for a crude oil spill to induce heritable mutations and impact natural populations.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  The primary environmental impact following an oil spill typically is acute toxicity to fish and wildlife. However, multigenerational effects through toxicant-induced heritable mutations might also occur. Some polycyclic aromatic hydrocarbon (PAH) components of crude oil are potentially mutagenic, although specific components and doses that induce mutations are poorly known. We applied population genetics concepts to assess the extent of mortality and the persistence of deleterious heritable mutations resulting from exposure to potential mutagens, such as crude oil. If lethal mutations are induced, the population will experience some mortality, but the mutations are quickly removed or reduced to low frequency by natural selection. This occurs within one or a few generations when mutations are dominant or partially recessive. Totally recessive alleles persist in low frequency for many gene rations, but result in relatively little impact on the population, depending on the number of mutated loci. We also applied population genetics concepts to assess the potential for heritable mutations induced by the Exxon Valdez oil spill in Prince William Sound, Alaska, to affect pink salmon populations. We stress that breeding units (e.g., streams with distinct spawning populations of salmon) must be considered individually to assess heritable genetic effects. For several streams impacted by the oil spill, there is inconsistency between observed egg mortality and that expected if lethal heritable mutations had been induced by exposure to crude oil. Observed mortality was either higher or lower than expected depending on the spawning population, year, and cohort considered. Any potential subtle effect of lethal mutations induced by the Exxon Valdez oil spill is overridden by natural env ironmental variation among spawning areas. We discuss the need to focus on population-level effects in toxicological assessments because fish and wildlife management focuses on populations, not individuals.</AbstractText>
<AU>CRONIN MA</AU>
<AU>BICKHAM JW</AU>
<Affiliation>LGL Alaska Research Associates, Inc., 4175 Tudor Centre Drive, Suite 202, Anchorage, AK, USA.</Affiliation>
<Year>1998</Year>
<Source>ECOTOXICOLOGY; 7 (5). 1998. 259-278.</Source>
<Keyword>Genetics and Cytogenetics-Animal</Keyword>
<Keyword>Ecology</Keyword>
<Keyword>Toxicology-General</Keyword>
<Keyword>Chordata</Keyword>
<Keyword>Pisces-Unspecified</Keyword>
<SecondarySourceID>BIOSIS/00/03742</SecondarySourceID>
<DOCNO>BIOSIS/00/03742</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>LIOCA</Coden>
<MeshHeading>ECOLOGY</MeshHeading>
<MeshHeading>ANATOMY, COMPARATIVE</MeshHeading>
<MeshHeading>ANIMAL</MeshHeading>
<MeshHeading>INSECTS/PHYSIOLOGY</MeshHeading>
<MeshHeading>PHYSIOLOGY, COMPARATIVE</MeshHeading>
<MeshHeading>PATHOLOGY</MeshHeading>
<MeshHeading>ALGAE</MeshHeading>
<MeshHeading>ALGAE</MeshHeading>
<MeshHeading>DIPTERA</MeshHeading>
<ArticleTitle>Effects of agriculture, urbanization, and climate on water quality in the northern Great Plains.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  The Qu'Appelle Valley drainage system provides water to a third of the population of the Canadian Great Plains, yet is plagued by poor water quality, excess plant growth, and periodic fish kills. Fossil algae (diatoms, pigments) and invertebrates (chironomids) in Pasqua Lake were analyzed by variance partitioning analysis (VPA) to determine the relative importance of climate, resource use, and urbanization as controls of aquatic community composition 1920-1994. From fossil analyses, we identified three distinct biological assemblages in Pasqua Lake. Prior to agriculture (ca. 1776-1890), the lake was naturally eutrophic with abundant cyanobacterial carotenoids (myxoxanthophyll, aphanizophyll), eutrophic diatoms (Stephanodiscus niagarae, Aulacoseira granulata, Fragilaria capucina/bidens), and anoxia-tolerant chironomids (Chironomus). Principal components (PCA) and dissimilarity analyses de monstrated that diatom and chironomid communities did not vary significantly (P &gt; 0.05) before European settlement. Communities changed rapidly during early land settlement (ca. 1890-1930) before forming a distinct assemblage ca. 1930-1960 characterized by elevated algal biomass (inferred as beta-carotene), nuisance cyanobacteria, eutrophic Stephanodiscus hantzschii, and low abundance of deep-water zoobenthos. Recent fossil assemblages (1977-1994) were variable and indicated water quality had not improved despite 3-fold reduction in phosphorus from sewage. Comparison of fossil community change and continuous annual records of 83 environmental variables (1890-1994) using VPA captured 71-97% of variance in fossil composition using only 10-14 significant factors. Resource use (cropland area, livestock biomass) and urbanization (nitrogen in sewage) were stronger determinants of algal and chiron omid community change than were climatic factors (temperature, evaporation, river discharge). Landscape analysis of inferred changes in past algal abundance (as beta-carotene; ca. 1780-1994) indicated that urban impacts declined with distance from point sources and suggested that management strategies will vary with lake position within the catchment.</AbstractText>
<AU>HALL RI</AU>
<AU>LEAVITT PR</AU>
<AU>QUINLAN R</AU>
<AU>DIXIT AS</AU>
<AU>SMOL JP</AU>
<Affiliation>Limnology Laboratory, Department of Biology, University of Regina, Regina, SK, Canada.</Affiliation>
<Year>1999</Year>
<Source>LIMNOLOGY AND OCEANOGRAPHY; 44 (3 PART 2). 1999. 739-756.</Source>
<Keyword>Ecology</Keyword>
<Keyword>Invertebrata</Keyword>
<Keyword>Algae-Unspecified</Keyword>
<Keyword>Chrysophyta</Keyword>
<Keyword>Diptera</Keyword>
<SecondarySourceID>BIOSIS/00/03743</SecondarySourceID>
<DOCNO>BIOSIS/00/03743</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<CASRegistryNumber>14265-44-2</CASRegistryNumber>
<CASRegistryNumber> 14265-44-2</CASRegistryNumber>
<CASRegistryNumber> 14797-55-8</CASRegistryNumber>
<CASRegistryNumber> 7440-66-6</CASRegistryNumber>
<CASRegistryNumber> 7440-50-8</CASRegistryNumber>
<CASRegistryNumber> 7440-43-9</CASRegistryNumber>
<CASRegistryNumber> 7440-38-2</CASRegistryNumber>
<CASRegistryNumber> 7440-02-0</CASRegistryNumber>
<Language>eng</Language>
<Coden>LIOCA</Coden>
<MeshHeading>ECOLOGY</MeshHeading>
<MeshHeading>ANIMAL</MeshHeading>
<MeshHeading>PHYSIOLOGY, COMPARATIVE</MeshHeading>
<MeshHeading>PROTOZOA/ULTRASTRUCTURE</MeshHeading>
<MeshHeading>PROTOZOA/PHYSIOLOGY</MeshHeading>
<MeshHeading>PATHOLOGY</MeshHeading>
<MeshHeading>ANATOMY, COMPARATIVE</MeshHeading>
<MeshHeading>ANIMAL</MeshHeading>
<MeshHeading>CRUSTACEA</MeshHeading>
<MeshHeading>PHYSIOLOGY, COMPARATIVE</MeshHeading>
<MeshHeading>PATHOLOGY</MeshHeading>
<MeshHeading>BACTERIA</MeshHeading>
<MeshHeading>PLANTS</MeshHeading>
<MeshHeading>INVERTEBRATES</MeshHeading>
<MeshHeading>MASTIGOPHORA</MeshHeading>
<MeshHeading>CRUSTACEA</MeshHeading>
<MeshHeading>FISHES</MeshHeading>
<ArticleTitle>Variability in responses to nutrients and trace elements, and transmission of stressor effects through an estuarine food web.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  Aquatic systems are increasingly exposed to multiple stressors from anthropogenic sources. These stressors can vary in the consistency and magnitude of responses they elicit in biota and in how the presence of additional stressors modifies their effects. Understanding how the biological environment and temporal dynamics influence responses to stressors, and how stressors interact, is important to predicting their effects in the natural environment. We examined temporal variability in responses of an experimental estuarine food web to elevated trace elements and nutrients, as well as non-additive effects of the combination of these two stressors. Experiments were conducted four times during spring through autumn 1996 in 20 l-m3 mesocosms. We measured a range of system-, population-, and individual-level parameters to quantify responses of phytoplankton, bacterioplankton, heterotrophic nan oflagellates, copepods, fish, and benthic invertebrates to trace element and nutrient additions. The response to trace element additions was more variable both temporally and among phytoplankton and higher trophic level taxa than was the response to nutrient additions. Most taxa increased, either significantly or showed a trend toward increasing, in response to nutrient additions in all four mesocosm runs. In contrast, the direction as well as the magnitude of responses to trace element additions varied considerably among taxa and experimental runs. Two distinct types of nutrient trace element interactions were important. First, temporal dynamics of nutrient ratios appeared to affect the temporal pattern of toxicity of trace elements to phytoplankton. Second, in the June mesocosm run when trace element additions reduced production, abundance, or growth of many organisms, these reductions  were often proportionately greater in nutrient addition tanks than where no nutrients were added. Our results suggest that considerable temporal and taxonomic variation in responses to trace element loadings are likely to be seen in field settings even under constant loadings to the system and that trace elements may mask the magnitude of the response to high nutrient loadings in eutrophic systems. More generally, the presence of multiple stressors may either increase or dampen the temporal and spatial variability seen in aquatic systems, depending on the interactions among stressors and the influence of background environmental conditions and sensitive species on the expression of stressor effects.</AbstractText>
<AU>BREITBURG DL</AU>
<AU>SANDERS JG</AU>
<AU>GILMOUR CC</AU>
<AU>HATFIELD CA</AU>
<AU>OSMAN RW</AU>
<AU>RIEDEL GF</AU>
<AU>SEITZINGER SP</AU>
<AU>SELLNER KG</AU>
<Affiliation>Academy of Natural Sciences, Estuarine Research Center, 10545 Mackall Road, Saint Leonard, MD, USA.</Affiliation>
<Year>1999</Year>
<Source>LIMNOLOGY AND OCEANOGRAPHY; 44 (3 PART 2). 1999. 837-863.</Source>
<Keyword>Ecology</Keyword>
<Keyword>Invertebrata</Keyword>
<Keyword>Invertebrata</Keyword>
<Keyword>Bacteria-General Unspecified (1992- )</Keyword>
<Keyword>Plantae-Unspecified</Keyword>
<Keyword>Invertebrata-Unspecified</Keyword>
<Keyword>Flagellata</Keyword>
<Keyword>Copepoda</Keyword>
<Keyword>Pisces-Unspecified</Keyword>
<SecondarySourceID>BIOSIS/00/03744</SecondarySourceID>
<DOCNO>BIOSIS/00/03744</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<CASRegistryNumber>1336-36-3</CASRegistryNumber>
<CASRegistryNumber> 1336-36-3</CASRegistryNumber>
<CASRegistryNumber> 34883-41-5</CASRegistryNumber>
<CASRegistryNumber> 41411-63-6</CASRegistryNumber>
<CASRegistryNumber> 33284-54-7</CASRegistryNumber>
<Language>eng</Language>
<Coden>LIOCA</Coden>
<MeshHeading>ECOLOGY</MeshHeading>
<MeshHeading>AIR POLLUTION</MeshHeading>
<MeshHeading>SOIL POLLUTANTS</MeshHeading>
<MeshHeading>WATER POLLUTION</MeshHeading>
<ArticleTitle>Biogeochemical cycling of PCBs in lakes of variable trophic status: A paired-lake experiment.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  A paired whole-lake experiment was conducted on two remote, atmospherically driven lakes in the Experimental Lakes Area (ELA) to examine the stresses of trophic condition on air-water exchange and settling fluxes of polychlorinated biphenyls (PCBs). Lake 227 (L227) and Lake 110 (L110) are similar in volume, surface area, and watershed area but differ significantly in trophic status. The two lakes have similar access to atmospheric PCBs but eutrophic L227 may exhibit enhanced air to water exchange due to greater biotic uptake of dissolved PCBs. Settling fluxes of PCB were significantly greater in eutrophic L227 (40 ng m-2 d-1 in 1993; 29 ng m-2 d-1 in 1994) than in oligotrophic L110 (22 ng m-2 d-1 in 1993 and 17 ng m-2 d-1 in 1994). Dissolved SIGMAPCB concentrations were not significantly different in the two lakes ( 0.3 ng liter-1). Greater SIGMAPCB settling fluxes in L227 vs. L110 coupled with  similar dissolved concentrations after June supports the hypothesis that air-water exchange supports the water column PCB concentrations. Surprisingly, SIGMAPCB fugacity gradients in both lakes indicated that net volatilization dominated during the entire ice-free period, requiring another source. A SIGMAPCB mass budget in the epilimnion of each lake over the stratified period showed that the major PCB losses were due to settling and volatilization. SIGMAPCB settling losses were 2.4 times greater in L227 than in L110 due to higher settling particle fluxes. The mass budgets suggest that the major PCB input to these remote lakes is from the watershed. Our results indicate the intimate environmental linkage between atmospheric, land, and aquatic PCB reservoirs.</AbstractText>
<AU>JEREMIASON JD</AU>
<AU>EISENREICH SJ</AU>
<AU>PATERSON MJ</AU>
<AU>BEATY KG</AU>
<AU>HECKY R</AU>
<AU>ELSER JJ</AU>
<Affiliation>Department of Environmental Sciences, Rutgers University, New Brunswick, NJ, USA.</Affiliation>
<Year>1999</Year>
<Source>LIMNOLOGY AND OCEANOGRAPHY; 44 (3 PART 2). 1999. 889-902.</Source>
<Keyword>Ecology</Keyword>
<Keyword>Public Health: Environmental Health-Air</Keyword>
<SecondarySourceID>BIOSIS/00/03745</SecondarySourceID>
<DOCNO>BIOSIS/00/03745</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>LIOCA</Coden>
<MeshHeading>ECOLOGY</MeshHeading>
<MeshHeading>AIR POLLUTION</MeshHeading>
<MeshHeading>SOIL POLLUTANTS</MeshHeading>
<MeshHeading>WATER POLLUTION</MeshHeading>
<MeshHeading>ANIMAL</MeshHeading>
<MeshHeading>ANIMALS, LABORATORY</MeshHeading>
<MeshHeading>ANIMALS, WILD</MeshHeading>
<MeshHeading>PARASITIC DISEASES/VETERINARY</MeshHeading>
<ArticleTitle>How environmental stress affects the impacts of parasites.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  Parasites occur in nearly every population. They often interact in complex ways with other stressors. In some cases, the interaction may lead to a disproportionately negative effect on the host population. In other cases, the stressor may ameliorate the effects of parasitism. Here we illustrate intersections of four types of environmental stressors with infectious diseases. First, pollutants may increase parasitism by increasing host susceptibility or by increasing the abundance of intermediate hosts and vectors. Pollutants can also decrease parasitism if infected hosts suffer differentially high mortality, parasites are more susceptible to pollution than their hosts, or if pollutants negatively affect intermediate hosts or vectors. These effects vary depending on the particular parasite and pollutant that interact. Second, habitat alterations such as impounding water or development can  affect both intermediate host and vector populations such that the abundance of their attendant parasites is either increased or reduced. Third, fisheries can impact populations already stressed by disease. However, they may act to lower the density of a host population below the threshold for sustained transmission to such an extent that the parasite population can no longer persist. Fourth, introduced species may introduce new diseases to susceptible native populations or they may gain an advantage if they invade without the parasites from their native range. The complexity and ubiquity of these interactions are good arguments for considering parasitism when evaluating stressors of aquatic systems.</AbstractText>
<AU>LAFFERTY KD</AU>
<AU>KURIS AM</AU>
<Affiliation>Department of Biological Sciences, Marine Science Institute, University of California, Santa Barbara, CA, USA.</Affiliation>
<Year>1999</Year>
<Source>LIMNOLOGY AND OCEANOGRAPHY; 44 (3 PART 2). 1999. 925-931.</Source>
<Keyword>Ecology</Keyword>
<Keyword>Public Health: Environmental Health-Air</Keyword>
<Keyword>Parasitology-General</Keyword>
<SecondarySourceID>BIOSIS/00/03746</SecondarySourceID>
<DOCNO>BIOSIS/00/03746</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>WSTED</Coden>
<MeshHeading>MATHEMATICS</MeshHeading>
<MeshHeading>STATISTICS</MeshHeading>
<MeshHeading>BIOLOGY</MeshHeading>
<MeshHeading>BIOCHEMISTRY</MeshHeading>
<MeshHeading>BACTERIA/PHYSIOLOGY</MeshHeading>
<MeshHeading>BACTERIA/METABOLISM</MeshHeading>
<MeshHeading>SANITATION</MeshHeading>
<MeshHeading>SEWAGE</MeshHeading>
<MeshHeading>BIODEGRADATION</MeshHeading>
<MeshHeading>INDUSTRIAL MICROBIOLOGY</MeshHeading>
<MeshHeading>BACTERIA</MeshHeading>
<ArticleTitle>Mathematical model for the biodegradation of VOCs in trickle bed biofilters.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  The objective of this work is to develop a fundamental mathematical model that describes the biodegradation of volatile organic compounds (VOCs) in gas phase trickle-bed biofilters, and to estimate the unknown model parameters. The mathematical model considers a three-phase system (biofilm, water, and gas phase), non-uniform bacterial population, and one limiting substrate. Two pilot-scale trickle-bed biofilters were operated to remove the VOC diethyl ether from a waste gas stream. Experimental results from this system were used to estimate the unknown parameters of the steady-state model: the maximum rate of substrate utilization mum Xf, the Monod constant, Ks, and the ether biofilm/water diffusivity ratio, rd. While the value of mum Xf/Y was uniquely determined, the values of Ks and rd, were highly correlated. High values of the Monod constant and the ether diffusivity in the biofilm g ave similar predictions to those corresponding to low values of both parameters. Batch studies were used to estimate the value of Ks without mass transfer limitations showing that Ks &lt; 1 mg/L=2.6 mg COD/L. Using this information and biofilter operating data the true values of Ks and rd were determined.</AbstractText>
<AU>ALONSO C</AU>
<AU>ZHU X</AU>
<AU>SUIDAN MT</AU>
<AU>KIM BR</AU>
<AU>KIM BJ</AU>
<Affiliation>Department of Civil and Environmental Engineering, University of Cincinnati, Cincinnati, OH, USA.</Affiliation>
<Year>1999</Year>
<Source>WATER SCIENCE AND TECHNOLOGY; 39 (7). 1999. 139-146.</Source>
<Keyword>Mathematical Biology and Statistical Methods</Keyword>
<Keyword>Biochemical Studies-General</Keyword>
<Keyword>Physiology and Biochemistry of Bacteria</Keyword>
<Keyword>Public Health: Environmental Health-Sewage Disposal and Sanitary Measures</Keyword>
<Keyword>Food and Industrial Microbiology-Biodegradation and Biodeterioration</Keyword>
<Keyword>Bacteria-General Unspecified (1992- )</Keyword>
<SecondarySourceID>BIOSIS/00/03747</SecondarySourceID>
<DOCNO>BIOSIS/00/03747</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>RTOPD</Coden>
<MeshHeading>POISONING</MeshHeading>
<MeshHeading>ANIMALS, LABORATORY</MeshHeading>
<MeshHeading>CARCINOGENS</MeshHeading>
<MeshHeading>HOMINIDAE</MeshHeading>
<ArticleTitle>A unified approach to risk assessment for cancer and noncancer endpoints based on benchmark doses and uncertainty-safety factors.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  A fundamental goal of toxicology is to determine safe levels of human exposure to toxic substances. In the absence of information to establish dose-response relationships at low exposure levels generally experienced by humans, high-dose to low-dose linear extrapolation is generally used for estimating carcinogenic risks and the no-observed-adverse-effect-level divided by uncertainty (safety) factors is widely used for establishing human exposure guidelines for noncancer effects. The basis and impact of this dichotomy is examined and questioned. It is proposed that a unified approach be adopted for establishing human exposure guidelines for both cancer and noncancer endpoints. It is suggested that a lower confidence limit on the dose estimated to produce an excess incidence of adverse health effects in 10% of the individuals in a human study or 10% of the animals in laboratory experiments  be used as a point-of-departure. This dose would be divided by appropriate uncertainty factors to establish human exposure guidelines. For severe irreversible adverse health effects we suggest a total default uncertainty factor (divisor) for animal data on the order of 10,000, which is comparable to current guidelines. For reversible biological effects a smaller default uncertainty factor on the order of 1000 may be employed. This is comparable to the divisor often used currently when the point-of-departure is the lowest-observed-adverse-effect-level. It is asserted that the toxicological information generally available does not warrant numerical estimates of risk at low levels of human exposure. Rather, we support a unified approach for all adverse health effects of dividing a benchmark dose by appropriate uncertainty factors to establish guidelines for human exposures to toxic substan ces.</AbstractText>
<AU>GAYLOR DW</AU>
<AU>KODELL RL</AU>
<AU>CHEN JJ</AU>
<AU>KREWSKI D</AU>
<Affiliation>National Center for Toxicological Research, U.S. Food and Drug Administration, Jefferson, AR, USA.</Affiliation>
<Year>1999</Year>
<Source>REGULATORY TOXICOLOGY AND PHARMACOLOGY; 29 (2 PART 1). 1999. 151-157.</Source>
<Keyword>Toxicology-General</Keyword>
<Keyword>Neoplasms and Neoplastic Agents-Carcinogens and Carcinogenesis</Keyword>
<Keyword>Hominidae</Keyword>
<SecondarySourceID>BIOSIS/00/03748</SecondarySourceID>
<DOCNO>BIOSIS/00/03748</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>BIPHE</Coden>
<MeshHeading>CYTOLOGY</MeshHeading>
<MeshHeading>HISTOCYTOCHEMISTRY</MeshHeading>
<MeshHeading>HUMAN</MeshHeading>
<MeshHeading>BIOCHEMISTRY</MeshHeading>
<MeshHeading>DIAGNOSIS</MeshHeading>
<MeshHeading>NERVOUS SYSTEM</MeshHeading>
<MeshHeading>POISONING</MeshHeading>
<MeshHeading>ANIMALS, LABORATORY</MeshHeading>
<MeshHeading>EPIDEMIOLOGIC METHODS</MeshHeading>
<MeshHeading>HERBICIDES</MeshHeading>
<MeshHeading>PEST CONTROL</MeshHeading>
<MeshHeading>PESTICIDES</MeshHeading>
<MeshHeading>HOMINIDAE</MeshHeading>
<ArticleTitle>Pesticides and Parkinson's disease.</ArticleTitle>
<AbstractText>BIOSIS  COPYRIGHT: BIOL ABS.  Epidemiological studies and case reports provide evidence for an association between Parkinson's disease and past exposure to pesticides. Susceptibility to the effects of pesticides and other putative neurotoxins depends on variability in xenobiotic metabolism possibly generated by genetic polymorphisms, aging and variation in exposure to environmental agents including pesticides. The simplest mechanistic hypothesis for the association of pesticides with Parkinson's disease is that pesticides or their metabolites are directly toxic to mitochondria, although modulation of xenobiotic metabolism by pesticides provides an adjunct or alternative hypothesis.</AbstractText>
<AU>LE COUTEUR DG</AU>
<AU>MCLEAN AJ</AU>
<AU>TAYLOR MC</AU>
<AU>WOODHAM BL</AU>
<AU>BOARD PG</AU>
<Affiliation>Canberra Clinical School of the University of Sydney, Canberra Hospital, Canberra, ACT, Australia.</Affiliation>
<Year>1999</Year>
<Source>BIOMEDICINE &amp; PHARMACOTHERAPY; 53 (3). 1999. 122-130.</Source>
<Keyword>Cytology and Cytochemistry-Human</Keyword>
<Keyword>Biochemical Studies-General</Keyword>
<Keyword>Nervous System-General</Keyword>
<Keyword>Toxicology-General</Keyword>
<Keyword>Public Health: Epidemiology-Miscellaneous</Keyword>
<Keyword>Pest Control</Keyword>
<Keyword>Hominidae</Keyword>
<SecondarySourceID>BIOSIS/00/03749</SecondarySourceID>
<DOCNO>BIOSIS/00/03749</DOCNO>
</DOC>
<DOC>
<EntryMonth>200005</EntryMonth>
<Language>eng</Language>
<Coden>JEMEA</Coden>
<MeshHeading>ANIMALS</MeshHeading>
<MeshHeading>CYTOLOGY</MeshHeading>
<MeshHeading>HISTOCYTOCHEMISTRY</MeshHeading>
<MeshHeading>ANIMALS/GENETICS</MeshHeading>
<MeshHeading>NUCLEIC ACIDS</MeshHeading>
<MeshHeading>PURINES</MeshHeading>
<MeshHeading>PYRIMIDINES</MeshHeading>
<MeshHeading>AMINO ACIDS</MeshHeading>
<MeshHeading>PEPTIDES</MeshHeading>
<MeshHeading>PROTEINS</MeshHeading>
<MeshHeading>ENZYMES/PHYSIOLOGY</MeshHeading>
<MeshHeading>BLOOD CELLS/ULTRASTRUCTURE</MeshHeading>
<MeshHeading>BLOOD CELLS/PHYSIOLOGY</MeshHeading>